### ISSUE TITLE
Set up Addin for Addin Registry

### ISSUE THREAD

**Issue by RickStrahl** [DVaughan/MarkdownMonster-Addin-TocGenerator#2]
This addin is a good candidate to be added into the Markdown Monster Addin Registry so it can show up in the Addin Manager.

More info here:
https://github.com/RickStrahl/MarkdownMonsterAddinsRegistry#creating-your-own-addin-and-adding-to-the-registry

I can't recall offhand but I think the main thing that needs to happen is using the **Build.ps1** command to create a **Build** folder at the Git root that contains the right files.

I can help set this up, but wanted to run this by you before issuing a PR.

**Comment by DVaughan** [comment]
Okay Rick. I'll do that for the toc addin and the figure auto number addin.

**Comment by DVaughan** [comment]
You'll see two pull requests. One for each of my addins.

**Comment by RickStrahl** [comment]
Checking out now - looks good at a glance.
