### ISSUE TITLE
Toc Version 1.2 on MM version 1.9.10 (or later) do not work!

### ISSUE THREAD

**Issue by Andis59** [DVaughan/MarkdownMonster-Addin-TocGenerator#6]
When I try to use your TOC 1.2 extension on MarkdownMonster version 1.9.10 or later, it does not create a Table of Context!

If I use the default **SampleMarkdown.md** I just get this
```
[//]: # (TOC Begin)

[//]: # (TOC End)

```

I has worked before but I can't recall which versions they work in!

Any clue on what can be the problem?

**Comment by Andis59** [comment]
I have now tested with MM 1.9.4 and TOC 1.2 and here it work perfectly!

So something has changed between 1.9.4 and 1.9.11

**Comment by Andis59** [comment]
OK, I have found the problem! When TOC splits the text into lines it uses Environment.NewLine (\r\n) but in MarkdownMonster version 1.9.10 and above it uses \n as End of Line.

Change this line in OnExecute()
`string[] lines = markdown.Split(new string[] { Environment.NewLine }, StringSplitOptions.None);
`
to 
`string[] lines = markdown.Split(new string[] { "\n" }, StringSplitOptions.None);
`
And TOC will work again.

The correct solution would probably be that MarkdownMonster use Environment.NewLine (My opinion!).

**Comment by DVaughan** [comment]
Thanks for looking into that, Anders. I've just committed an update.

Cheers,
Daniel
